[theme]
# Primary accent color for interactive elements.
primaryColor = "#3F51B5"

# Background color for the main content area.
backgroundColor = "#E0E0E0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#BDBDBD"

# Color used for almost all text.
textColor = "#212121"


